name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            ninja-build \
            curl \
            unzip \
            lib32z1 \
            lib32stdc++6 \
            libc6-i386 \
            libstdc++6 \
            libpulse0 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libnss3 \
            libncurses6 \
            libasound2t64
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Install Android Studio
        run: |
          # Download and extract Android Studio
          wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2023.1.1.26/android-studio-2023.1.1.26-linux.tar.gz
          sudo tar -xzf android-studio-2023.1.1.26-linux.tar.gz -C /opt/
          
          # Set environment variables
          echo "ANDROID_STUDIO_HOME=/opt/android-studio" >> $GITHUB_ENV
          echo "PATH=$PATH:/opt/android-studio/bin" >> $GITHUB_ENV
          
          # Create desktop entry
          sudo tee /usr/share/applications/android-studio.desktop << EOF
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=Android Studio
          Exec=/opt/android-studio/bin/studio.sh
          Icon=/opt/android-studio/bin/studio.png
          Terminal=false
          StartupNotify=true
          Categories=Development;IDE;
          EOF
          
          # Set permissions
          sudo chmod +x /opt/android-studio/bin/studio.sh
          
      - name: Setup Android SDK
        run: |
          # Set environment variables
          export ANDROID_HOME=/opt/android/sdk
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV
          
          # Create SDK directory
          sudo mkdir -p $ANDROID_HOME
          sudo chown -R $USER:$USER $ANDROID_HOME
          
          # Download and install Command line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          mkdir -p $ANDROID_HOME/cmdline-tools
          mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # Install required SDK packages
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0" \
            "extras;android;m2repository" \
            "extras;google;m2repository" \
            "cmdline-tools;latest"
          
          # Accept licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          
      - name: Configure Flutter
        run: |
          flutter config --no-analytics
          flutter config --android-sdk /opt/android/sdk
          flutter config --android-studio-dir /opt/android-studio
          flutter doctor -v
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet flet-core
          
      - name: Debug Environment
        run: |
          echo "Python version:"
          python --version
          echo "Pip packages:"
          pip list
          echo "Flutter version:"
          flutter --version
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Source directory contents:"
          ls -la src/
          echo "Android Studio location:"
          echo $ANDROID_STUDIO_ROOT
          
      - name: Build APK with Debug
        run: |
          echo "Starting APK build..."
          cd simple-counter
          flet build apk --verbose --module-name src.main
          echo "Build complete"
          echo "Checking build output directory:"
          ls -R build/
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: simple-counter/build/app/outputs/flutter-apk/app-release.apk